### ISSUE TITLE
What are possible detection vectors using this?

### ISSUE THREAD

**Issue by Sinclairq** [btbd/modmap#20]
Unrelated topic, thanks though.

**Comment by btbd** [comment]
> BE/EAC can check the syscall table to ensure it hasn't been modified

This doesn't modify any service descriptor tables, besides those are protected by PG. It does modify a function pointer residing in the kernel's data section if that's what you mean.

The detection vectors of this are:
1. DLL's size in memory not matching its SizeOfImage.
2. DLL memory marked as MEM_PRIVATE instead of MEM_IMAGE.

You can't realistically get around the first one, but the second one you can just edit the VAD but you'll have to revert it before the process exits.

**Comment by Sinclairq** [comment]
Thanks

**Comment by btbd** [comment]
@Sinclairq Yes, you could modify this repository to map your DLL into an existing RWX section of another DLL.
