### ISSUE TITLE
Question to btbd

### ISSUE THREAD

**Issue by FocuzJS** [btbd/modmap#25]
@btbd How does it feel to have single handedly destroyed the Fortnite section and give retards like UnfairGame something to directly paste and sell? Not to mention the people still pasting Maven and calcshotcaller in 2020 😳. Seems to me you're directly responsible for this..?
Asking for a friend. @BerkanYildiz

**Comment by BerkanYildiz** [comment]
Code Monkey.

The term "code monkey" refers to a person who writes computer code for a living, specifically those who grind out fairly routine code rather than performing the more intellectually complex tasks such as software architecture, analysis, and design. As such, the term may be considered by some to be derogatory, and it is usually applied to more junior "programmers".

"Code Monkeys" are also considered to lack intellectual capability in seeing the "Big Picture" and are often myopic when it comes to business sense. They are typically characterized to be content with their insignificant status and are often depicted to be bad with women, lacking basic social skills.

It may also be used self-deprecatingly in griping about or denying responsibility for management decisions (e.g. "Don't ask me why we have to allocate in NonPagedPool, I'm just a code monkey").

**Comment by Object9999** [comment]
Anyone got calculateshot sig?

**Comment by EggsyCRO** [comment]
yo I think I found calcshotcaller sig can someone help me use it with modmapper please?

**Comment by BerkanYildiz** [comment]
apparently @btbd and mehmet the unfairgames pasted p2c owner can help you @EggsyCRO 👀

**Comment by FocuzJS** [comment]
Is this the Fortnite section or where I'm gonna get my reply from @btbd? Because I sure can't tell.

**Comment by Object9999** [comment]
i think its 5A 4D ??

**Comment by Sinclairq** [comment]
> i think its 5A 4D ??

Should be 0x4550 

Also it wasn't btbd's fault any of this happened lol I mean maybe he did things that triggered such events but who cares he released something for people to learn not paste, guess he learned his lesson.

**Comment by btbd** [comment]
Feels great to know people still obsess over my worst projects 😉

**Comment by PineconePaster9000** [comment]
How to compile exe it make it txt file

**Comment by BerkanYildiz** [comment]
Unfortunately all your projects are your "worst" projects

**Comment by btbd** [comment]
@BerkanYildiz Hence why these projects are public 😛

**Comment by FocuzJS** [comment]
> 
> 
> > i think its 5A 4D ??
> 
> Should be 0x4550
> 
> Also it wasn't btbd's fault any of this happened lol I mean maybe he did things that triggered such events but who cares he released something for people to learn not paste, guess he learned his lesson.

shut it paster

> 
> 
> > i think its 5A 4D ??
> 
> Should be 0x4550
> 
> Also it wasn't btbd's fault any of this happened lol I mean maybe he did things that triggered such events but who cares he released something for people to learn not paste, guess he learned his lesson.

shut it paster
