### ISSUE TITLE
Failed to find module "dxgi.dll"

### ISSUE THREAD

**Issue by xAyman** [btbd/modmap#7]
Hey,
I used modmap today to inject my dll into FortniteClient-Win64-Shipping.exe
Also, i tried d3d11.dll and it can't find the module, i also tried with dxgi.dll but it's still not working ;(
If you can help me, thank you very much.
Have a nice day ;) !

**Comment by btbd** [comment]
@xAyman Is the driver successfully loaded? The CLI app will always fail with “module not found” if it cannot communicate with the driver.

**Comment by Hoeko** [comment]
Sorry for hijacking on that issue, but since you mentioned the driver. Is there any reason why it wont load with kdmapper ? Other drivers are working just fine. I even tried to copy the code to another driver project which im sure it will work. DriverEntry never gets called. https://i.imgur.com/1Ox54hy.png

**Comment by xAyman** [comment]
Sorry, i made a mistake and the driver wasn't loaded correctly.
Thanks for your help.
